Remove input read indices, make reference index optional and combine same sample together
sanger-tol/variantcalling pull request #59
Opened 2023-10-07 16:09 UTC by gq1

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/variantcalling/tree/main/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-10-07 18:50 UTC, gq1 commented
@nf-core-bot fix linting

2023-10-13 07:27 UTC, muffato reviewed
- Push the updated `samtools merge` to nf-core
- Update `bin/check_samplesheet.py` not to append the `_T*` suffixes so that you don't need the `replaceAll`

2023-10-13 07:43 UTC, priyanka-surana requested changes
Initial review. I think we should clean up the pipeline logic a bit before adding the next set of features. Thinking about what we need and what is just adding complexity. Yet to run tests.

2023-10-13 07:43 UTC, priyanka-surana commented on modules/nf-core/samtools/merge/samtools-merge.diff
Rerun patch after changes are made.

2023-11-02 12:30 UTC, gq1 commented on modules/nf-core/samtools/merge/main.nf
> +    tuple val(meta4), path(gzi)
These 2 fields have been combined like all other nf-core samtools modules.

2023-11-02 12:33 UTC, gq1 commented on modules/nf-core/samtools/merge/meta.yml
> +      pattern: "*.gzi"
The pattern has not been updated. We better updated all other nf-core samtools modules together.

From the other side, this **\*.fai** pattern doesn't stop you to pass **gzi** file into the module, just make it clear for users.

2023-11-02 12:35 UTC, gq1 commented
> * Push the updated `samtools merge` to nf-core
The patch being pushed to nf-core and updated. https://github.com/nf-core/modules/pull/4258

> * Update `bin/check_samplesheet.py` not to append the `_T*` suffixes so that you don't need the `replaceAll`
The script being updated only validate the samplesheet not transform it. https://github.com/sanger-tol/variantcalling/pull/59/commits/d6fa00f37eb2729b6c67b3d0a4d36f02e1536b35

2023-11-02 12:36 UTC, gq1 commented on subworkflows/local/input_merge.nf
> +    gzi                // file: /path/to/genome.fasta.gz.gzi or null
two being combined into one as **fai** now

2023-11-02 12:37 UTC, gq1 commented on workflows/variantcalling.nf
> +if (params.gzi)     { ch_gzi   = Channel.fromPath(params.gzi)         } else { ch_gzi      = Channel.empty() }
combine them now but still allow users to pass the index file in.

2023-11-02 12:37 UTC, gq1 commented on modules/nf-core/samtools/merge/samtools-merge.diff
no patch needed now.

2023-11-02 12:39 UTC, gq1 commented on nextflow.config
> +    sort_input                 = false
The sort flag being removed now and always do a sort for now just in case the merging to fail.
Hope sorting a sorted bam/carm file should be fast.

2023-11-02 14:07 UTC, gq1 commented on subworkflows/local/input_filter_split.nf
> +    ch_fasta = fasta.map { fasta -> [ [ 'id': fasta.baseName ], fasta ] }.first()
fasta being used a bit differently in subworkflows. Only add the meta id when necessary.
I will keep like this for now.

2023-11-02 14:14 UTC, gq1 commented
1. patch for **samtools/merge** module being pushed to nf-core
2. combine **fai** and **gzi** input fields for samtool/merge module but didn't update the pattern, following all other cases in samtools modules
3. combine **fai** and **gzi** parameters for the whole workflow
4. remove sort_input parameters and sorting input bam/cram before merging
5. not changing the sample names in sample_checking script

2023-11-03 12:17 UTC, muffato approved these changes

2023-11-03 13:33 UTC, merged